# Generated by Django 4.0.6 on 2022-07-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('code', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('message_text', models.CharField(max_length=200)),
                ('end_time', models.DateTimeField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(verbose_name='date send')),
                ('status', models.CharField(choices=[('S', 'SEND'), ('A', 'AWAITING'), ('F', 'FAILED')], default='A', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client')),
                ('related_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail')),
            ],
        ),
    ]
