# Generated by Django 4.0.6 on 2022-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='filter',
            field=models.CharField(default='', max_length=256),
        ),
    ]
