# Generated by Django 4.0.6 on 2022-07-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mail_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='filter',
            new_name='mail_filter',
        ),
    ]
