# Generated by Django 4.0.6 on 2022-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_code_tag_remove_mail_mail_filter_remove_client_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='code_filter',
        ),
        migrations.AddField(
            model_name='mail',
            name='code_filter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='tag_filter',
        ),
        migrations.AddField(
            model_name='mail',
            name='tag_filter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
